"""add_form_field_date_config

Revision ID: ceb88963b2e6
Revises: d95a07857418
Create Date: 2026-07-16 04:21:41.863499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceb88963b2e6'
down_revision: Union[str, Sequence[str], None] = 'd95a07857418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT enum_range(NULL::formfieldtype)")).scalar()
    if 'DATE' not in str(result):
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE formfieldtype ADD VALUE 'DATE'")
            
    op.add_column('form_fields', sa.Column('date_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_fields', 'date_config')
    # ### end Alembic commands ###
