"""add_notes_version

Revision ID: d95a07857418
Revises: 560803566961
Create Date: 2026-07-15 23:18:54.662062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd95a07857418'
down_revision: Union[str, Sequence[str], None] = '560803566961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('version', sa.INTEGER(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'version')
    # ### end Alembic commands ###
